#                                    Лабораторная работа №7

## Pandas: Обработка данных

**1.** Описание исходных данных приведено тут: https://www.kaggle.com/janiobachmann/math-students. Вам предложены измененные данные.

In [ ]:
# Открываем таблицу с данными об учениках
import pandas as pd
data = pd.read_csv('math_students.csv', delimiter=',')

In [ ]:
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
3,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
4,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15

Проанализируйте данные - выведите всю возможную информацию, типы данных, распределение по каждому столбцу.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423 entries, 0 to 422
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      423 non-null    object
 1   sex         423 non-null    object
 2   age         423 non-null    int64
 3   address     423 non-null    object
 4   famsize     423 non-null    object
 5   Pstatus     423 non-null    object
 6   Medu        423 non-null    int64
 7   Fedu        423 non-null    int64
 8   Mjob        420 non-null    object
 9   Fjob        423 non-null    object
 10  reason      422 non-null    object
 11  guardian    421 non-null    object
 12  traveltime  423 non-null    int64
 13  studytime   423 non-null    int64
 14  failures    423 non-null    int64
 15  schoolsup   423 non-null    object
 16  famsup      421 non-null    object
 17  paid        423 non-null    object
 18  activities  423 non-null    object
 19  nursery     423 non-null    object
 20  higher      423 non-null    object
 21  internet    423 non-null    object
 22  romantic    423 non-null    object
 23  famrel      423 non-null    int64
 24  freetime    423 non-null    int64
 25  goout       423 non-null    int64
 26  Dalc        423 non-null    int64
 27  Walc        423 non-null    int64
 28  health      423 non-null    int64
 29  absences    423 non-null    int64
 30  G1          423 non-null    int64
 31  G2          423 non-null    int64
 32  G3          423 non-null    int64
dtypes: int64(16), object(17)
memory usage: 109.2+ KB

При наличии нелогичных данных или пустых значений - постарайтесь исправить то, что можно, а при невозможности исправления, удалите соответствующие строки. Фиксируйте, какие изменения вы выполняете.

In [ ]:
# Анализ типов данных и распределения
for col in data.columns:
    print(f"Столбец: {col}")
    print(f"Тип данных: {data[col].dtype}")
    print(f"Уникальные значения: {data[col].unique()}")
    print(f"Распределение: {data[col].value_counts().head()}")
    print(data[col].describe())
    print()

In [ ]:
# Обработка столбца 'Pstatus' (нелогичное значение 'А')
data['Pstatus'] = data['Pstatus'].replace("А", "A")

# Обработка столбца 'guardian' (нелогичное значение 'fatherfather')
data['guardian'] = data['guardian'].replace("fatherfather", "father")

# Обработка столбца 'guardian' (нелогичное значение 'bestmother')
data['guardian'] = data['guardian'].replace("bestmother", "mother")

# Обработка столбца 'internet' (нелогичное значение 'yess')
data['internet'] = data['internet'].replace("yess", "yes")

# Обработка столбца 'activities' (нелогичное значение 'YES')
data['activities'] = data['activities'].replace("YES", "yes")

# Обработка столбца 'romantic' (нелогичное значение 'noo')
data['romantic'] = data['romantic'].replace("noo", "no")

# Обработка столбца 'famrel' (нелогичное значение 366 - вероятно, ошибка ввода)
data['famrel'] = data['famrel'].replace(366, 5)

# Обработка столбца 'Mjob' (nan)
data['Mjob'] = data['Mjob'].fillna("other")

# Обработка столбца 'reason' (nan)
data['reason'] = data['reason'].fillna("other")

# Обработка столбца 'guardian' (nan)
data['guardian'] = data['guardian'].fillna("other")

Если в таблице имеются повторяющиеся строки - удалите их.

In [ ]:
duplicates = data.duplicated()
print(duplicates)
data.drop_duplicates(inplace=True)
duplicates = data.duplicated()
print("Если в таблице имеются повторяющиеся строки - удалите их")
print(duplicates)

0      False
1      False
2      False
3      False
4      False
       ...
418     True
419     True
420     True
421     True
422     True
Length: 423, dtype: bool
Если в таблице имеются повторяющиеся строки - удалите их
0      False
1      False
2      False
3      False
4      False
       ...
409    False
410    False
411    False
413    False
414    False
Length: 402, dtype: bool

После предобработки данных визуализируйте распределение значений всех столбцов.

In [ ]:
# Анализ типов данных и распределения
for col in data.columns:
    print(f"Столбец: {col}")
    print(f"Тип данных: {data[col].dtype}")
    print(f"Уникальные значения: {data[col].unique()}")
    print(f"Распределение: {data[col].value_counts().head()}")
    print(data[col].describe())
    print()

Столбец: school
Тип данных: object
Уникальные значения: ['GP' 'MS']
Распределение: school
GP    353
MS     49
Name: count, dtype: int64
count     402
unique      2
top        GP
freq      353
Name: school, dtype: object

Столбец: sex
Тип данных: object
Уникальные значения: ['F' 'M' 'N']
Распределение: sex
F    211
M    190
N      1
Name: count, dtype: int64
count     402
unique      3
top         F
freq      211
Name: sex, dtype: object

Столбец: age
Тип данных: int64
Уникальные значения: [18 17 15 16 19 22 20 21]
Распределение: age
16    104
17    100
18     85
15     84
19     24
Name: count, dtype: int64
count    402.000000
mean      16.699005
std        1.275688
min       15.000000
25%       16.000000
50%       17.000000
75%       18.000000
max       22.000000
Name: age, dtype: float64

Столбец: address
Тип данных: object
Уникальные значения: ['U' 'R' 'UU' 'RR']
Распределение: address
U     312
R      87
UU      2
RR      1
Name: count, dtype: int64
count     402
unique      4
top         U
freq      312
Name: address, dtype: object

Столбец: famsize
Тип данных: object
Уникальные значения: ['GT3' 'LE3']
Распределение: famsize
GT3    286
LE3    116
Name: count, dtype: int64
count     402
unique      2
top       GT3
freq      286
Name: famsize, dtype: object

Столбец: Pstatus
Тип данных: object
Уникальные значения: ['A' 'T']
Распределение: Pstatus
T    358
A     44
Name: count, dtype: int64
count     402
unique      2
top         T
freq      358
Name: Pstatus, dtype: object

Столбец: Medu
Тип данных: int64
Уникальные значения: [4 1 3 2 0]
Распределение: Medu
4    132
2    107
3    101
1     59
0      3
Name: count, dtype: int64
count    402.000000
mean       2.746269
std        1.089647
min        0.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        4.000000
Name: Medu, dtype: float64

Столбец: Fedu
Тип данных: int64
Уникальные значения: [4 1 2 3 0]
Распределение: Fedu
2    116
3    104
4     97
1     83
0      2
Name: count, dtype: int64
count    402.000000
mean       2.524876
std        1.085211
min        0.000000
25%        2.000000
50%        2.500000
75%        3.000000
max        4.000000
Name: Fedu, dtype: float64

Столбец: Mjob
Тип данных: object
Уникальные значения: ['at_home' 'services' 'health' 'other' 'teacher' 'healths']
Распределение: Mjob
other       144
services    104
at_home      61
teacher      58
health       34
Name: count, dtype: int64
count       402
unique        6
top       other
freq        144
Name: Mjob, dtype: object

Столбец: Fjob
Тип данных: object
Уникальные значения: ['teacher' 'other' 'services' 'health' 'at_home' 'service']
Распределение: Fjob
other       220
services    114
teacher      29
at_home      20
health       18
Name: count, dtype: int64
count       402
unique        6
top       other
freq        220
Name: Fjob, dtype: object

Столбец: reason
Тип данных: object
Уникальные значения: ['course' 'home' 'other' 'reputation']
Распределение: reason
course        147
home          111
reputation    107
other          37
Name: count, dtype: int64
count        402
unique         4
top       course
freq         147
Name: reason, dtype: object

Столбец: guardian
Тип данных: object
Уникальные значения: ['mother' 'father' 'other']
Распределение: guardian
mother    277
father     91
other      34
Name: count, dtype: int64
count        402
unique         3
top       mother
freq         277
Name: guardian, dtype: object

Столбец: traveltime
Тип данных: int64
Уникальные значения: [2 1 3 4]
Распределение: traveltime
1    260
2    110
3     23
4      9
Name: count, dtype: int64
count    402.000000
mean       1.455224
std        0.705684
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        4.000000
Name: traveltime, dtype: float64

Столбец: studytime
Тип данных: int64
Уникальные значения: [2 3 1 4]
Распределение: studytime
2    202
1    107
3     65
4     28
Name: count, dtype: int64
count    402.000000
mean       2.034826
std        0.840841
min        1.000000
25%        1.000000
50%        2.000000
75%        2.000000
max        4.000000
Name: studytime, dtype: float64

Столбец: failures
Тип данных: int64
Уникальные значения: [0 3 2 1]
Распределение: failures
0    319
1     50
2     17
3     16
Name: count, dtype: int64
count    402.000000
mean       0.328358
std        0.738430
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        3.000000
Name: failures, dtype: float64

Столбец: schoolsup
Тип данных: object
Уникальные значения: ['yes' 'no']
Распределение: schoolsup
no     350
yes     52
Name: count, dtype: int64
count     402
unique      2
top        no
freq      350
Name: schoolsup, dtype: object

Столбец: famsup
Тип данных: object
Уникальные значения: ['no' 'yes' nan]
Распределение: famsup
yes    248
no     153
Name: count, dtype: int64
count     401
unique      2
top       yes
freq      248
Name: famsup, dtype: object

Столбец: paid
Тип данных: object
Уникальные значения: ['no' 'yes']
Распределение: paid
no     217
yes    185
Name: count, dtype: int64
count     402
unique      2
top        no
freq      217
Name: paid, dtype: object

Столбец: activities
Тип данных: object
Уникальные значения: ['no' 'yes']
Распределение: activities
yes    204
no     198
Name: count, dtype: int64
count     402
unique      2
top       yes
freq      204
Name: activities, dtype: object

Столбец: nursery
Тип данных: object
Уникальные значения: ['yes' 'no']
Распределение: nursery
yes    319
no      83
Name: count, dtype: int64
count     402
unique      2
top       yes
freq      319
Name: nursery, dtype: object

Столбец: higher
Тип данных: object
Уникальные значения: ['yes' 'long' 'no']
Распределение: higher
yes     381
no       20
long      1
Name: count, dtype: int64
count     402
unique      3
top       yes
freq      381
Name: higher, dtype: object

Столбец: internet
Тип данных: object
Уникальные значения: ['no' 'yes']
Распределение: internet
yes    336
no      66
Name: count, dtype: int64
count     402
unique      2
top       yes
freq      336
Name: internet, dtype: object

Столбец: romantic
Тип данных: object
Уникальные значения: ['no' 'yes']
Распределение: romantic
no     265
yes    137
Name: count, dtype: int64
count     402
unique      2
top        no
freq      265
Name: romantic, dtype: object

Столбец: famrel
Тип данных: int64
Уникальные значения: [4 5 3 1 2]
Распределение: famrel
4    198
5    109
3     68
2     18
1      9
Name: count, dtype: int64
count    402.000000
mean       3.945274
std        0.905505
min        1.000000
25%        4.000000
50%        4.000000
75%        5.000000
max        5.000000
Name: famrel, dtype: float64

Столбец: freetime
Тип данных: int64
Уникальные значения: [3 2 4 1 5]
Распределение: freetime
3    160
4    116
2     67
5     40
1     19
Name: count, dtype: int64
count    402.000000
mean       3.226368
std        0.996753
min        1.000000
25%        3.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: freetime, dtype: float64

Столбец: goout
Тип данных: int64
Уникальные значения: [4 3 2 1 5]
Распределение: goout
3    135
2    105
4     86
5     53
1     23
Name: count, dtype: int64
count    402.000000
mean       3.101990
std        1.106339
min        1.000000
25%        2.000000
50%        3.000000
75%        4.000000
max        5.000000
Name: goout, dtype: float64

Столбец: Dalc
Тип данных: int64
Уникальные значения: [1 2 5 3 4]
Распределение: Dalc
1    281
2     75
3     26
5     10
4     10
Name: count, dtype: int64
count    402.000000
mean       1.490050
std        0.910537
min        1.000000
25%        1.000000
50%        1.000000
75%        2.000000
max        5.000000
Name: Dalc, dtype: float64

Столбец: Walc
Тип данных: int64
Уникальные значения: [1 3 2 4 5]
Распределение: Walc
1    153
2     87
3     81
4     51
5     30
Name: count, dtype: int64
count    402.000000
mean       2.298507
std        1.294703
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max        5.000000
Name: Walc, dtype: float64

Столбец: health
Тип данных: int64
Уникальные значения: [3 1 5 2 4]
Распределение: health
5    146
3     95
4     68
1     48
2     45
Name: count, dtype: int64
count    402.000000
mean       3.544776
std        1.385437
min        1.000000
25%        3.000000
50%        4.000000
75%        5.000000
max        5.000000
Name: health, dtype: float64

Столбец: absences
Тип данных: int64
Уникальные значения: [ 6  4  0 10  2 16 14  7  8 25 12  9 54 18 26 20 56 24 28  5 13 15 22  3
 21  1 75 30 19 11 38 40 23 17]
Распределение: absences
0    118
2     66
4     54
6     32
8     22
Name: count, dtype: int64
count    402.000000
mean       5.674129
std        7.961615
min        0.000000
25%        0.000000
50%        4.000000
75%        8.000000
max       75.000000
Name: absences, dtype: float64

Столбец: G1
Тип данных: int64
Уникальные значения: [ 5 16  7 15  6 12 14 10 13  8 11  9 17 19 18  4  3]
Распределение: G1
10    52
8     42
11    42
7     37
12    35
Name: count, dtype: int64
count    402.00000
mean      10.91791
std        3.30506
min        3.00000
25%        8.00000
50%       11.00000
75%       13.00000
max       19.00000
Name: G1, dtype: float64

Столбец: G2
Тип данных: int64
Уникальные значения: [ 6  5 18  8 14 10 15 12 16 13  9 11  7 19 17  4  0]
Распределение: G2
9     50
10    48
12    41
13    38
11    36
Name: count, dtype: int64
count    402.000000
mean      10.718905
std        3.755374
min        0.000000
25%        9.000000
50%       11.000000
75%       13.000000
max       19.000000
Name: G2, dtype: float64

Столбец: G3
Тип данных: int64
Уникальные значения: [   6   19   10   15   11    9   12   14   16    5    8   17   18   13
   20    7    0    4 6785]
Распределение: G3
10    58
11    47
0     38
15    33
12    32
Name: count, dtype: int64
count     402.000000
mean       27.283582
std       337.915584
min         0.000000
25%         8.000000
50%        11.000000
75%        14.000000
max      6785.000000
Name: G3, dtype: float64

Следующие задания выполните на предобработанных данных.

* Какая причина выбора школы была самой частой? В качестве ответа приведите соответствующее значение признака.

In [ ]:
data["reason"].mode()

0    course
Name: reason, dtype: object

* Найдите количество студентов, у родителей (одного или обоих - рассмотрите оба варианта) которых нет никакого образования.

In [ ]:
print(len(data[(data['Fedu'] == 0) | (data['Medu'] == 0)]))
print(len(data[(data['Fedu'] == 0) & (data['Medu'] == 0)]))

5
0

* Найдите минимальный возраст учащегося школы Mousinho da Silveira.

In [ ]:
min_age = data.groupby(['school'])['age'].agg(['min'])
min_age

        min
school
GP       15
MS       17

* Найдите количество студентов, имеющих нечетное число пропусков.

In [ ]:
print(len(data[(data['absences'] % 2 == 1)]))

41

* Найдите разность между средними итоговыми оценками студентов, состоящих и не состоящих в романтических отношениях. В качестве ответа приведите число, округленное до двух значащих цифр после запятой.

In [ ]:
data["Final_grades"] = round((data["G1"]+data["G2"]+data["G3"])/3,2)
data.head()
#romantic_diff = round(data.groupby(['romantic'])['Final_grades'].agg(['mean']),2)
romantic_diff = data[data['romantic'] == "yes"]["Final_grades"].mean() - data[data['romantic'] == "no"]["Final_grades"].mean()
print(round(romantic_diff,2))

15.65

* Сколько занятий пропустило большинство студентов с самым частым значением наличия внеклассных активностей?

*Примечание. В данном контексте под "большинством" подразумеваются студенты, имеющее самое частое значение пропусков. То есть в данном задании необходимо:*


* *Определить самое частое значение наличия внеклассных активностей (да или нет).*
* *Для группы студентов, соответствующей этому значению, рассмотреть значения признака «число пропусков».*
* *Для каждого значения числа пропусков посчитать, сколько студентов ему соответствует.*
* *Выбрать значение числа пропусков с наибольшим числом студентов.*

In [ ]:
# 1. Определяем самое частое значение признака 'activities'
most_common_activities = data["activities"].mode()[0]

# 2. Фильтруем студентов с этим значением
filtered_data = data[data["activities"] == most_common_activities]

# 3. Подсчитываем количество студентов для каждого значения числа пропусков
absences_counts = filtered_data["absences"].value_counts()

# 4. Исключаем 0 (непропустивших студентов)
absences_counts = absences_counts[absences_counts.index != 0]

# 5. Определяем самое частое ненулевое количество пропусков
most_common_nonzero_absences = absences_counts.idxmax()

# Вывод результата
print(f"Наиболее частое ненулевое количество пропусков: {most_common_nonzero_absences}")
print(f"Количество студентов с этим числом пропусков: {absences_counts.max()}")

Наиболее частое ненулевое количество пропусков: 2
Количество студентов с этим числом пропусков: 38

**2.** Возьмите свой набор данных (или выберите, например, на kaggle). Выполните различные возможные операции по предобработке и первичному анализу данных.

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

import kagglehub

# Download latest version
path = kagglehub.dataset_download("atharvasoundankar/futuristic-smart-city-citizen-activity-dataset")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/atharvasoundankar/futuristic-smart-city-citizen-activity-dataset?dataset_version_number=1...

100%|██████████| 22.9k/22.9k [00:00<00:00, 18.4MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/atharvasoundankar/futuristic-smart-city-citizen-activity-dataset/versions/1

In [9]:
smart_city = pd.read_csv('/content/drive/MyDrive/Программирование на языке Python/Lab_Python_7_PIM/smart_city_citizen_activity.csv')
smart_city.head()

,Citizen_ID,Age,Gender,Mode_of_Transport,Work_Hours,Shopping_Hours,Entertainment_Hours,Home_Energy_Consumption_kWh,Charging_Station_Usage,Carbon_Footprint_kgCO2,Steps_Walked,Calories_Burned,Sleep_Hours,Social_Media_Hours,Public_Events_Hours
0,1001,56,Female,Walking,5,2,0,5.32,0,44.70,15635,975,9.2,5.8,0.5
1,1002,69,Male,Bicycle,0,2,2,2.19,0,92.39,1671,455,8.1,5.5,1.9
2,1003,46,Male,Bike,0,4,0,4.68,0,78.57,1777,324,4.7,3.8,2.8
3,1004,32,Male,Car,7,2,3,3.42,0,55.46,4022,537,4.9,3.5,0.5
4,1005,60,Male,Walking,3,3,1,2.79,0,98.95,19244,1414,6.6,2.2,0.5

In [10]:
if smart_city is not None:
    print("\nПервые 5 строк датасета:")
    print(df.head())

    print("\nИнформация о датасете:")
    df.info()

    print("\nОписательная статистика для числовых столбцов:")
    print(df.describe())

    print("\nРазмерность датасета (строки, столбцы):")
    print(df.shape)

    print("\nНазвания столбцов:")
    print(df.columns)

Первые 5 строк датасета:
       crim        zn     indus      chas       nox        rm       age  \
0 -0.419782  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013
1 -0.417339 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166
2 -0.417342 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812
3 -0.416750 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889
4 -0.412482 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180

        dis       rad       tax   ptratio         b     lstat  medv
0  0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  24.0
1  0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439  21.6
2  0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  34.7
3  1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517  33.4
4  1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501  36.2

Информация о датасете:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    float64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    float64
 9   tax      506 non-null    float64
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB

Описательная статистика для числовых столбцов:
               crim            zn         indus          chas           nox  \
count  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02
mean  -1.123388e-16  7.898820e-17  2.106352e-16 -3.510587e-17 -1.965929e-16
std    1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00
min   -4.197819e-01 -4.877224e-01 -1.557842e+00 -2.725986e-01 -1.465882e+00
25%   -4.109696e-01 -4.877224e-01 -8.676906e-01 -2.725986e-01 -9.130288e-01
50%   -3.906665e-01 -4.877224e-01 -2.110985e-01 -2.725986e-01 -1.442174e-01
75%    7.396560e-03  4.877224e-02  1.015999e+00 -2.725986e-01  5.986790e-01
max    9.933931e+00  3.804234e+00  2.422565e+00  3.668398e+00  2.732346e+00

                 rm           age           dis           rad         tax  \
count  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02  506.000000
mean  -1.088282e-16 -1.474446e-16 -8.425408e-17 -1.123388e-16    0.000000
std    1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00    1.000990
min   -3.880249e+00 -2.335437e+00 -1.267069e+00 -9.828429e-01   -1.313990
25%   -5.686303e-01 -8.374480e-01 -8.056878e-01 -6.379618e-01   -0.767576
50%   -1.084655e-01  3.173816e-01 -2.793234e-01 -5.230014e-01   -0.464673
75%    4.827678e-01  9.067981e-01  6.623709e-01  1.661245e+00    1.530926
max    3.555044e+00  1.117494e+00  3.960518e+00  1.661245e+00    1.798194

            ptratio             b         lstat        medv
count  5.060000e+02  5.060000e+02  5.060000e+02  506.000000
mean  -4.212704e-16 -7.442444e-16 -3.089316e-16   22.532806
std    1.000990e+00  1.000990e+00  1.000990e+00    9.197104
min   -2.707379e+00 -3.907193e+00 -1.531127e+00    5.000000
25%   -4.880391e-01  2.050715e-01 -7.994200e-01   17.025000
50%    2.748590e-01  3.811865e-01 -1.812536e-01   21.200000
75%    8.065758e-01  4.336510e-01  6.030188e-01   25.000000
max    1.638828e+00  4.410519e-01  3.548771e+00   50.000000

Размерность датасета (строки, столбцы):
(506, 14)

Названия столбцов:
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [11]:
# Проверка на наличие пропущенных значений
print("Пропущенные значения в датасете:")
print(smart_city.isnull().sum())

# Стандартизация данных
scaler = StandardScaler()
smart_city_scaled = pd.DataFrame(scaler.fit_transform(smart_city), columns=smart_city.columns)

print("\nДатасет после стандартизации:")
print(smart_city_scaled.head())

# Выявление выбросов
Q1 = smart_city.quantile(0.25)
Q3 = smart_city.quantile(0.75)
IQR = Q3 - Q1

print("\nВыбросы в датасете:")
print((smart_city < (Q1 - 1.5 * IQR)) | (smart_city > (Q3 + 1.5 * IQR)))

# Анализ корреляции между признаками
correlation_matrix = smart_city.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='coolwarm', center=0)
plt.title("Матрица корреляции")
plt.show()

# Визуализация данных
sns.pairplot(smart_city)
plt.suptitle("Парные графики", y=1.02)
plt.show()

Пропущенные значения в датасете:
Citizen_ID                     0
Age                            0
Gender                         0
Mode_of_Transport              0
Work_Hours                     0
Shopping_Hours                 0
Entertainment_Hours            0
Home_Energy_Consumption_kWh    0
Charging_Station_Usage         0
Carbon_Footprint_kgCO2         0
Steps_Walked                   0
Calories_Burned                0
Sleep_Hours                    0
Social_Media_Hours             0
Public_Events_Hours            0
dtype: int64

ValueError: could not convert string to float: 'Female'